In [1]:
import numpy as np
import tensorflow as tf

In [2]:
X_val = np.load('./X_val.npy')
y_val = np.load('./y_val.npy')

In [3]:
sess = tf.InteractiveSession()

In [4]:
saver = tf.train.import_meta_graph('./model/test-10.meta')

In [5]:
saver.restore(sess, './model/test-10')

INFO:tensorflow:Restoring parameters from ./model/test-10


In [6]:
graph = tf.get_default_graph()

In [11]:
graph.get_tensor_by_name('next_h_0:0')

<tf.Tensor 'next_h_0:0' shape=(1, 128) dtype=float32>

In [13]:
state_c_0 = graph.get_tensor_by_name('state_c_0:0')
state_h_0 = graph.get_tensor_by_name('state_h_0:0')

state_c_1 = graph.get_tensor_by_name('state_c_1:0')
state_h_1 = graph.get_tensor_by_name('state_h_1:0')

state_c_2 = graph.get_tensor_by_name('state_c_2:0')
state_h_2 = graph.get_tensor_by_name('state_h_2:0')

In [14]:
next_c_0 = graph.get_tensor_by_name('next_c_0:0')
next_h_0 = graph.get_tensor_by_name('next_h_0:0')

next_c_1 = graph.get_tensor_by_name('next_c_1:0')
next_h_1 = graph.get_tensor_by_name('next_h_1:0')

next_c_2 = graph.get_tensor_by_name('next_c_2:0')
next_h_2 = graph.get_tensor_by_name('next_h_2:0')

In [16]:
x_in = graph.get_tensor_by_name('x_in:0')
out_bid = graph.get_tensor_by_name('out_bid:0')

In [17]:
seq_in = graph.get_tensor_by_name('seq_in:0')
keep_prob = graph.get_tensor_by_name('keep_prob:0')

In [18]:
out_bid_logit = graph.get_tensor_by_name('out_bid_logit:0')

In [21]:
x = np.zeros((1, 179))
z = np.zeros((1, 128))
b0 = sess.run(out_bid, feed_dict={keep_prob: 1.0, x_in:x, state_c_0:z, state_h_0:z, state_c_1:z, state_h_1:z, state_c_2:z, state_h_2:z})
n_c_0 = sess.run(next_c_0, feed_dict={keep_prob: 1.0, x_in:x, state_c_0:z, state_h_0:z, state_c_1:z, state_h_1:z, state_c_2:z, state_h_2:z})

In [23]:
n_c_0

array([[  5.06054237e-03,  -3.10771074e-03,   4.91264742e-03,
         -4.98362584e-03,   4.80592251e-03,   1.32603815e-03,
          4.93980851e-03,   2.54831719e-03,  -5.02184685e-03,
         -4.60709300e-04,  -4.51021595e-03,   4.95940680e-03,
         -4.64065978e-03,  -4.80556814e-03,  -5.06168604e-03,
          4.47626662e-04,  -2.87332805e-04,   4.87677846e-03,
         -4.99222009e-03,  -3.10570817e-03,  -4.65495931e-03,
         -4.98911273e-03,   1.45426451e-03,   3.43274628e-03,
          4.91423812e-03,  -4.88411356e-03,   4.84299520e-03,
          5.05603058e-03,   4.92216041e-03,  -3.32629937e-03,
          4.88230493e-03,  -3.21280560e-03,   4.92790109e-03,
         -2.70800083e-03,  -2.83682323e-03,   4.80473880e-03,
          4.96561639e-03,  -4.67975438e-03,   3.27432901e-03,
         -5.02366014e-03,  -4.85972269e-03,  -4.86623123e-03,
         -4.84419474e-03,  -1.74183643e-03,   4.93982481e-03,
          4.99388948e-03,  -3.10293864e-03,  -4.97603510e-03,
        

In [19]:
bids = sess.run(out_bid_logit, feed_dict={seq_in: X_val[0:1, 0:1], keep_prob: 1.0})

In [22]:
bids

array([[-25.80791664,  -9.33546734,  -2.7819128 ,  -6.53328896,
        -25.92403221,  -5.27107382,  -6.20774603,  10.26448536,
         -3.29983425,  -7.1399045 ,  -6.18421268,  -8.07068157,
         -4.1593771 , -11.01375294,  -7.52219439,  -7.62676764,
         -9.0797081 ,  -9.77803993, -12.84655952, -12.37415791,
        -14.97718143, -20.7016716 , -11.13573456, -20.58936119,
        -24.46537971, -18.08568954, -23.33672142, -39.07943344,
        -64.59513092, -14.25973701, -35.92338181, -45.35156631,
        -41.93603134, -54.34156418, -12.36878586, -44.40045547,
        -45.70103073, -28.52837563, -36.65755081, -33.71347809]], dtype=float32)

In [23]:
sess.run(tf.nn.softmax(bids))

array([[  2.15750859e-16,   3.07501180e-09,   2.15784053e-06,
          5.06777091e-08,   1.92098589e-16,   1.79056741e-07,
          7.01776912e-08,   9.99995589e-01,   1.28554984e-06,
          2.76291416e-08,   7.18487598e-08,   1.08927178e-08,
          5.44244699e-07,   5.74085501e-10,   1.88512868e-08,
          1.69795378e-08,   3.97120248e-09,   1.97532946e-09,
          9.18329232e-11,   1.47285587e-10,   1.09064016e-11,
          3.56096276e-14,   5.08160736e-10,   3.98421124e-14,
          8.26054906e-16,   4.87162611e-13,   2.55375351e-15,
          3.71712218e-22,   3.08232619e-33,   2.23492631e-11,
          8.72695337e-21,   7.01865916e-25,   2.13600435e-23,
          8.74878353e-29,   1.48079077e-10,   1.81683857e-24,
          4.94861518e-25,   1.42060131e-17,   4.18810066e-21,
          7.95447767e-20]], dtype=float32)