In [1]:
import numpy as np
import random

distr = np.array([
    np.array([5,3,3,2]) / 13,
    np.array([1,6,4,2]) / 13,
    np.array([4,2,4,3]) / 13,
    np.array([3,2,2,6]) / 13
])

hcp = np.array([18, 10, 3, 9]) / 52

rank_val = {0: 4, 1: 3, 2: 2, 3: 1}

In [2]:
CARDS = np.arange(52)

In [3]:
distr

array([[ 0.38461538,  0.23076923,  0.23076923,  0.15384615],
       [ 0.07692308,  0.46153846,  0.30769231,  0.15384615],
       [ 0.30769231,  0.15384615,  0.30769231,  0.23076923],
       [ 0.23076923,  0.15384615,  0.15384615,  0.46153846]])

In [8]:
def deal(distr, hcp):
    np.random.shuffle(CARDS)
    hands = np.zeros((4, 52), np.byte)
    n_cards = np.array([0, 0, 0, 0])
    hand_hcp = np.array([0, 0, 0, 0])
    card_i = 0
    n_rejects = 0
    while np.sum(n_cards) < 52:
        
        #import pdb; pdb.set_trace()
        card = CARDS[card_i]
        suit = card // 13
        worth = rank_val.get(card % 13, 0)
        w_worth = worth / 52
#         params = (w_worth * hcp) + ((1 - w_worth) * distr[suit])
#         params = params / np.sum(params)
        #params = hcp if worth > 0 else distr[suit]
        params = distr[suit]
        wnes = np.random.multinomial(1, params)
        hand_i = np.argmax(wnes)
        if n_cards[hand_i] >= 13:
            n_rejects += 1
            hands = np.zeros((4, 52), np.byte)
            n_cards = np.array([0, 0, 0, 0])
            hand_hcp = np.array([0, 0, 0, 0])
            card_i = 0
            continue
        hands[hand_i, card] = 1
        hand_hcp[hand_i] += worth
        n_cards[hand_i] += 1
        card_i += 1
    
    return n_rejects, np.sum(hands.reshape((4,4,13)), axis=2), hand_hcp

In [9]:
deal(distr, hcp)

(392, array([[5, 0, 3, 5],
        [5, 5, 2, 1],
        [2, 4, 5, 2],
        [1, 4, 3, 5]]), array([ 9, 17,  6,  8]))

In [10]:
X = np.zeros((100, 4, 4))
H = np.zeros((100, 4))

for i in range(100):
    _, x, h = deal(distr, hcp)
    X[i,:,:] = x
    H[i,:] = h

In [11]:
np.mean(X, axis=0), np.mean(H, axis=0)

(array([[ 5.  ,  0.95,  4.02,  3.03],
        [ 2.79,  6.22,  2.02,  1.97],
        [ 3.04,  3.86,  4.02,  2.08],
        [ 2.17,  1.97,  2.94,  5.92]]),
 array([  9.69,  10.67,   9.69,   9.95]))

In [37]:
cards = np.array([0,1,2,3,4,4,4])

In [38]:
samples = np.zeros((5000, len(cards)), np.int)

In [39]:
samples[:,:] = cards

In [40]:
samples[:5,:]

array([[0, 1, 2, 3, 4, 4, 4],
       [0, 1, 2, 3, 4, 4, 4],
       [0, 1, 2, 3, 4, 4, 4],
       [0, 1, 2, 3, 4, 4, 4],
       [0, 1, 2, 3, 4, 4, 4]])

In [41]:
shuffler = np.vectorize(np.random.permutation, signature='(n)->(n)')

In [43]:
shuffled_samples = shuffler(samples)

In [44]:
shuffled_samples

array([[3, 0, 1, ..., 4, 2, 4],
       [4, 2, 4, ..., 4, 1, 3],
       [4, 4, 1, ..., 0, 2, 4],
       ..., 
       [2, 3, 4, ..., 1, 4, 4],
       [2, 4, 0, ..., 3, 4, 1],
       [4, 4, 0, ..., 4, 2, 3]])

In [45]:
cards_1, cards_2 = shuffled_samples[:,:3], shuffled_samples[:,3:]

In [47]:
cards_2

array([[4, 4, 2, 4],
       [0, 4, 1, 3],
       [3, 0, 2, 4],
       ..., 
       [0, 1, 4, 4],
       [4, 3, 4, 1],
       [1, 4, 2, 3]])

In [98]:
hand_1 = np.zeros((5000, 8), np.float16)
hand_2 = np.zeros((5000, 8), np.float16)

In [94]:
hand_2[:2,:]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float16)

In [51]:
hand_2[:, cards_2] = 1

In [52]:
hand_2[:2,:]

array([[ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.]], dtype=float16)

In [54]:
cards_2.T

array([[4, 0, 3, ..., 0, 4, 1],
       [4, 4, 0, ..., 1, 3, 4],
       [2, 1, 2, ..., 4, 4, 2],
       [4, 3, 4, ..., 4, 1, 3]])

In [57]:
cards_2

array([[4, 4, 2, 4],
       [0, 4, 1, 3],
       [3, 0, 2, 4],
       ..., 
       [0, 1, 4, 4],
       [4, 3, 4, 1],
       [1, 4, 2, 3]])

In [59]:
hand_2[:, cards_2[]]

(5000, 8)

In [60]:
cards_2.shape

(5000, 4)

In [74]:
hand_2[cards_2[:,0]] = 1

In [75]:
hand_2[0]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float16)

In [72]:
hand_2

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float16)

In [96]:
cards_2

array([[4, 4, 2, 4],
       [0, 4, 1, 3],
       [3, 0, 2, 4],
       ..., 
       [0, 1, 4, 4],
       [4, 3, 4, 1],
       [1, 4, 2, 3]])

In [87]:
hand_2[:,:] = np.arange(8)

In [92]:
hand_2[:3,[1, 2, 3]]

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]], dtype=float16)

In [85]:
hand_2[0, cards_2[0]] += 1

In [86]:
hand_2[0, :]

array([ 0.,  1.,  3.,  3.,  5.,  5.,  6.,  7.], dtype=float16)

In [89]:
hand_2.T.shape

(8, 5000)

In [90]:
np.vectorize?

In [110]:
%%timeit
hand_2 = np.zeros((5000, 8), np.float16)
row_indexes = np.arange(hand_2.shape[0])
for k in range(cards_2.shape[1]):
    hand_2[row_indexes, cards_2[:, k]] += 1

533 µs ± 4.01 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [106]:
hand_2[:, 0:5]

array([[ 0.,  0.,  1.,  0.,  3.],
       [ 1.,  1.,  0.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  0.,  0.,  2.],
       [ 0.,  1.,  0.,  1.,  2.],
       [ 0.,  1.,  1.,  1.,  1.]], dtype=float16)

In [101]:
cards_2

array([[4, 4, 2, 4],
       [0, 4, 1, 3],
       [3, 0, 2, 4],
       ..., 
       [0, 1, 4, 4],
       [4, 3, 4, 1],
       [1, 4, 2, 3]])

In [109]:
(np.sum(hand_2, axis=1) == 4).all()

True